### ISSUE TITLE
MOJARRA_2_2X_ROLLING branch fails to build

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4224]
Steps to reproduce:

1.  Clear out your **<tt>$MOJARRA_HOME/dependencies</tt>** folder:```
    rm -r dependencies/*
    ```

2.  Build the <tt>MOJARRA_2_2X_ROLLING</tt> branch ([if you get a different error, you may need to follow the steps here](http://stackoverflow.com/questions/10964606/how-to-build-mojarra-from-source#32825725)):```
    ant main clean main
    ```

If the bug still exists, the build will fail with the following error message:

```
update:
    [mkdir] Created dir: /Users/kylestiemann/Projects/oracle.com/mojarra/dependencies/downloads
    [mkdir] Created dir: /Users/kylestiemann/Projects/oracle.com/mojarra/dependencies/jars
      [get] Getting: http://repo1.maven.org/maven2/org/glassfish/ant-tasks/3.1.1/ant-tasks-3.1.1.jar
      [get] To: /Users/kylestiemann/Projects/oracle.com/mojarra/dependencies/jars/ant-tasks.jar
      [get] Getting: http://repo1.maven.org/maven2/junit/junit/3.8.1/junit-3.8.1.jar
      [get] To: /Users/kylestiemann/Projects/oracle.com/mojarra/dependencies/jars/junit-3.8.1.jar
      [get] Getting: http://downloads.sourceforge.net/htmlunit/htmlunit-2.4.zip
      [get] To: /Users/kylestiemann/Projects/oracle.com/mojarra/dependencies/downloads/htmlunit-2.4.zip
      [get] http://downloads.sourceforge.net/htmlunit/htmlunit-2.4.zip permanently moved to http://downloads.sourceforge.net/project/htmlunit/htmlunit/2.4/htmlunit-2.4.zip
      [get] http://downloads.sourceforge.net/project/htmlunit/htmlunit/2.4/htmlunit-2.4.zip moved to https://superb-sea2.dl.sourceforge.net/project/htmlunit/htmlunit/2.4/htmlunit-2.4.zip
      [get] Error getting http://downloads.sourceforge.net/htmlunit/htmlunit-2.4.zip to /Users/kylestiemann/Projects/oracle.com/mojarra/dependencies/downloads/htmlunit-2.4.zip 
BUILD FAILED
/Users/kylestiemann/Projects/oracle.com/mojarra/build.xml:127: The following error occurred while executing this line:
/Users/kylestiemann/Projects/oracle.com/mojarra/build.xml:89: The following error occurred while executing this line:
/Users/kylestiemann/Projects/oracle.com/mojarra/common/ant/dependencies.xml:231: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
        at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:728)
        at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:748)
        at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:748)
        at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:641)
        at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:631)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unableto find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1323)
        ... 15 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
        ... 21 more

Total time: 5 seconds
```

If the bug is fixed, the build will succeed.
#### Affected Versions
[2.2.14, 2.2.15]

**Comment by stiemannkj1** [comment]
Here's an updated script that can workaround this issue:

**`prepare-mojarra-2.2.x-build.sh`**:

```
#!/bin/bash

set -e
git apply <<'EOF'
diff --git a/common/ant/dependencies.xml b/common/ant/dependencies.xml
index a582395..f849e2c 100644
--- a/common/ant/dependencies.xml
+++ b/common/ant/dependencies.xml
@@ -228,7 +228,7 @@
             <then>
                 <get src="http://downloads.sourceforge.net/htmlunit/htmlunit-${htmlunit.version}.zip"
                      dest="${dependency.base.dir}/downloads/htmlunit-${htmlunit.version}.zip"
-                     usetimestamp="true"/>
+                     usetimestamp="true" ignoreerrors="true"/>
                 <unzip
                         src="${dependency.base.dir}/downloads/htmlunit-${htmlunit.version}.zip"
                         dest="${dependency.base.dir}"/>
@@ -248,7 +248,7 @@
             <then>
                 <get src="http://downloads.sourceforge.net/project/xs3p/xs3p-${xs3p.version}.zip"
                      dest="${dependency.base.dir}/downloads/xs3p-${xs3p.version}.zip"
-                     usetimestamp="true"/>
+                     usetimestamp="true" ignoreerrors="true"/>
                 <mkdir dir="${xs3p.home}" />
                 <unzip
                         src="${dependency.base.dir}/downloads/xs3p-${xs3p.version}.zip"
@@ -344,7 +344,7 @@
                 </not>
             </and>
             <then>
-                <get src="http://vdldoc.googlecode.com/files/vdldoc-${vdldoc.version}.jar"
+                <get src="http://vdldoc.omnifaces.org/downloads/vdldoc-${vdldoc.version}.jar"
                      dest="${vdldoc.jar}"
                      usetimestamp="true"/>
 
@@ -363,7 +363,7 @@
                 </not>
             </and>
             <then>
-                <get src="http://jsdoc-toolkit.googlecode.com/files/jsdoc_toolkit-${jsdoc.version}.zip"
+                <get src="https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/jsdoc-toolkit/jsdoc_toolkit-${jsdoc.version}.zip"
                      dest="${dependency.base.dir}/downloads/jsdoc_toolkit-${jsdoc.version}.zip"
                      usetimestamp="true"/>
                 <unzip
EOF

mkdir -p dependencies/downloads/
curl -o dependencies/downloads/htmlunit-2.4.zip 'https://cytranet.dl.sourceforge.net/project/htmlunit/htmlunit/2.4/htmlunit-2.4.zip'
curl -o dependencies/downloads/xs3p-1.1.5.zip 'http://cytranet.dl.sourceforge.net/project/xs3p/xs3p-1.1.5.zip'
```

Use it like this:

```
./prepare-mojarra-2.2.x-build.sh
ant main clean main
```

**Comment by stiemannkj1** [comment]
This has been fixed by https://github.com/javaserverfaces/mojarra/commit/25f801738e7ae1d068234d33a30ffd930223a751 (vdldoc link) and https://github.com/javaserverfaces/mojarra/commit/2c8164011919290762238ae23b2e126b024d1341 (jsdoc link).

However the errors on the sourceforge downloads are actually due to the fact that JDK 1.7 does not contain the correct certificates (it's likely the missing letsencrypt cert that is causing the problem). I solved this by downloading the latest JDK 8 and copying **`cacerts`** from there to JDK 7:

    cp $JDK_8_HOME/jre/lib/security/cacerts $JDK_7_HOME/jre/lib/security/cacerts
