### ISSUE TITLE
<f:validateWholeBean> broken when referencing a bean property

### ISSUE THREAD

**Issue by BalusC** [javaserverfaces/mojarra#4313]
`<f:validateWholeBean>` works fine when used directly on a managed bean as documented. 
```
<f:validateWholeBean value="#{backingBean}" />
```
However, it fails when used on a managed bean property.
```
<f:validateWholeBean value="#{backingBean.someEntity}" />
```
EL will throw the following exception:
```
Caused by: java.lang.IllegalArgumentException: Cannot convert com.sun.faces.ext.validateWholeBean of type class java.lang.String to class com.example.model.SomeEntity
	at com.sun.el.lang.ELSupport.coerceToType(ELSupport.java:428)
	at com.sun.el.lang.ELSupport.coerceToType(ELSupport.java:382)
	at com.sun.el.parser.AstValue.setValue(AstValue.java:248)
	at com.sun.el.ValueExpressionImpl.setValue(ValueExpressionImpl.java:294)
	at org.jboss.weld.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
	at org.jboss.weld.el.WeldValueExpression.setValue(WeldValueExpression.java:64)
	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:137)
	at javax.faces.component.UIInput.updateModel(UIInput.java:883)
	... 53 more
```
It turns out that `<f:validateWholeBean>` unintentionally executes the update model values phase as well. This has to be skipped in `UIValidateWholeBean`.

**Comment by BalusC** [comment]
Work around for now:
```
<f:validateWholeBean value="#{backingBean.someEntity}" rendered="#{facesContext.currentPhaseId.ordinal ne 4}" />
```

**Comment by BalusC** [comment]
To do: add unit test.

**Comment by BalusC** [comment]
IT has been added
